### ISSUE TITLE
Resolve extensionless imports

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollup-plugin-sucrase#3]
TypeScript yells at you if you do this...

```js
import foo from './foo.ts';
```

...instead of this:

```js
import foo from './foo';
```

I find that idiotic and infuriating but so be it. Perhaps this plugin could automatically resolve TypeScript imports without extensions, if you specify the `typescript` transform.

What do you reckon @alangpierce?

**Comment by Rich-Harris** [comment]
Fixed in 2.1.0

**Comment by StreetStrider** [comment]
Awesome. Closing another gap created by TS.
